id: I37EFE30E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T21:34:35+00:00'
last_modified: '2022-06-09T04:32:10.843543+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ45313
  title: བཀའ་འགྱུར། ༼ཧེ་མིས་བྲིས་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    455F:
      image_group_id: I4CZ75258
      title: Volume 1 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 513
      order: 1
      base_file: 455F.txt
    13D2:
      image_group_id: I4CZ75259
      title: Volume 2 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 412
      order: 2
      base_file: 13D2.txt
    2B0D:
      image_group_id: I4CZ75260
      title: Volume 3 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 855
      order: 3
      base_file: 2B0D.txt
    '6765':
      image_group_id: I4CZ75261
      title: Volume 4 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 917
      order: 4
      base_file: 6765.txt
    6CBD:
      image_group_id: I4CZ75262
      title: Volume 5 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 776
      order: 5
      base_file: 6CBD.txt
    '8049':
      image_group_id: I4CZ75263
      title: Volume 6 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 937
      order: 6
      base_file: 8049.txt
    BB0B:
      image_group_id: I4CZ75264
      title: Volume 7 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 903
      order: 7
      base_file: BB0B.txt
    CE99:
      image_group_id: I4CZ75265
      title: Volume 8 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 674
      order: 8
      base_file: CE99.txt
    0E03:
      image_group_id: I4CZ75266
      title: Volume 9 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 659
      order: 9
      base_file: 0E03.txt
    6E9F:
      image_group_id: I4CZ75267
      title: Volume 10 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 596
      order: 10
      base_file: 6E9F.txt
    DE8A:
      image_group_id: I4CZ75268
      title: Volume 11 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 664
      order: 11
      base_file: DE8A.txt
    '3728':
      image_group_id: I4CZ75269
      title: Volume 12 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 559
      order: 12
      base_file: 3728.txt
    4E26:
      image_group_id: I4CZ75270
      title: Volume 13 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 921
      order: 13
      base_file: 4E26.txt
    795B:
      image_group_id: I4CZ75271
      title: Volume 14 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 1031
      order: 14
      base_file: 795B.txt
    ED2A:
      image_group_id: I4CZ75272
      title: Volume 15 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 933
      order: 15
      base_file: ED2A.txt
    C694:
      image_group_id: I4CZ75273
      title: Volume 16 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 0
      order: 16
      base_file: C694.txt
    F8E8:
      image_group_id: I4CZ75274
      title: Volume 17 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 742
      order: 17
      base_file: F8E8.txt
    '1863':
      image_group_id: I4CZ75275
      title: Volume 18 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 934
      order: 18
      base_file: 1863.txt
    74BA:
      image_group_id: I4CZ75276
      title: Volume 19 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 1161
      order: 19
      base_file: 74BA.txt
    BC42:
      image_group_id: I4CZ75277
      title: Volume 20 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 957
      order: 20
      base_file: BC42.txt
    '4674':
      image_group_id: I4CZ75278
      title: Volume 21 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 898
      order: 21
      base_file: 4674.txt
    B558:
      image_group_id: I4CZ75279
      title: Volume 22 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 966
      order: 22
      base_file: B558.txt
    4FC4:
      image_group_id: I4CZ75280
      title: Volume 23 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 1148
      order: 23
      base_file: 4FC4.txt
    DB20:
      image_group_id: I4CZ75281
      title: Volume 24 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 994
      order: 24
      base_file: DB20.txt
    3F89:
      image_group_id: I4CZ75282
      title: Volume 25 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 762
      order: 25
      base_file: 3F89.txt
    9B8B:
      image_group_id: I4CZ75283
      title: Volume 26 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 754
      order: 26
      base_file: 9B8B.txt
    819D:
      image_group_id: I4CZ75284
      title: Volume 27 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 828
      order: 27
      base_file: 819D.txt
    EA9B:
      image_group_id: I4CZ75285
      title: Volume 28 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 778
      order: 28
      base_file: EA9B.txt
    E33A:
      image_group_id: I4CZ75286
      title: Volume 29 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 575
      order: 29
      base_file: E33A.txt
    F777:
      image_group_id: I4CZ75287
      title: Volume 30 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 668
      order: 30
      base_file: F777.txt
    14A9:
      image_group_id: I4CZ75288
      title: Volume 31 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 723
      order: 31
      base_file: 14A9.txt
    F342:
      image_group_id: I4CZ75289
      title: Volume 32 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 0
      order: 32
      base_file: F342.txt
    '4228':
      image_group_id: I4CZ75290
      title: Volume 33 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 1102
      order: 33
      base_file: 4228.txt
    0AE4:
      image_group_id: I4CZ75291
      title: Volume 34 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 1140
      order: 34
      base_file: 0AE4.txt
    0D07:
      image_group_id: I4CZ75292
      title: Volume 35 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 995
      order: 35
      base_file: 0D07.txt
    '4021':
      image_group_id: I4CZ75293
      title: Volume 36 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 1174
      order: 36
      base_file: 4021.txt
    90C2:
      image_group_id: I4CZ75294
      title: Volume 37 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 0
      order: 37
      base_file: 90C2.txt
    70A6:
      image_group_id: I4CZ75295
      title: Volume 38 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 0
      order: 38
      base_file: 70A6.txt
    27C2:
      image_group_id: I4CZ75296
      title: Volume 39 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 507
      order: 39
      base_file: 27C2.txt
    3A46:
      image_group_id: I4CZ75297
      title: Volume 40 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 490
      order: 40
      base_file: 3A46.txt
    '3720':
      image_group_id: I4CZ75298
      title: Volume 41 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 871
      order: 41
      base_file: 3720.txt
    F625:
      image_group_id: I4CZ75299
      title: Volume 42 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 589
      order: 42
      base_file: F625.txt
    '4360':
      image_group_id: I4CZ75300
      title: Volume 43 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 318
      order: 43
      base_file: 4360.txt
    '6246':
      image_group_id: I4CZ75301
      title: Volume 44 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 541
      order: 44
      base_file: 6246.txt
    2E1F:
      image_group_id: I4CZ75302
      title: Volume 45 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 0
      order: 45
      base_file: 2E1F.txt
    A415:
      image_group_id: I4CZ75303
      title: Volume 46 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 432
      order: 46
      base_file: A415.txt
    D574:
      image_group_id: I4CZ75304
      title: Volume 47 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 580
      order: 47
      base_file: D574.txt
    0D1B:
      image_group_id: I4CZ75305
      title: Volume 48 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 380
      order: 48
      base_file: 0D1B.txt
    8A1A:
      image_group_id: I4CZ75306
      title: Volume 49 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 528
      order: 49
      base_file: 8A1A.txt
    E45B:
      image_group_id: I4CZ75307
      title: Volume 50 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 484
      order: 50
      base_file: E45B.txt
    03C0:
      image_group_id: I4CZ75308
      title: Volume 51 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 500
      order: 51
      base_file: 03C0.txt
    EB7D:
      image_group_id: I4CZ75309
      title: Volume 52 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 528
      order: 52
      base_file: EB7D.txt
    F0F6:
      image_group_id: I4CZ75310
      title: Volume 53 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 550
      order: 53
      base_file: F0F6.txt
    E282:
      image_group_id: I4CZ75311
      title: Volume 54 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 677
      order: 54
      base_file: E282.txt
    B9C0:
      image_group_id: I4CZ75312
      title: Volume 55 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 602
      order: 55
      base_file: B9C0.txt
    '7828':
      image_group_id: I4CZ75313
      title: Volume 56 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 548
      order: 56
      base_file: 7828.txt
    A71B:
      image_group_id: I4CZ75314
      title: Volume 57 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 460
      order: 57
      base_file: A71B.txt
    743C:
      image_group_id: I4CZ75315
      title: Volume 58 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 545
      order: 58
      base_file: 743C.txt
    FA88:
      image_group_id: I4CZ75316
      title: Volume 59 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 645
      order: 59
      base_file: FA88.txt
    9D80:
      image_group_id: I4CZ75317
      title: Volume 60 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 439
      order: 60
      base_file: 9D80.txt
    86D7:
      image_group_id: I4CZ75318
      title: Volume 61 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 684
      order: 61
      base_file: 86D7.txt
    69FB:
      image_group_id: I4CZ75319
      title: Volume 62 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 512
      order: 62
      base_file: 69FB.txt
    B4E9:
      image_group_id: I4CZ75320
      title: Volume 63 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 614
      order: 63
      base_file: B4E9.txt
    '8631':
      image_group_id: I4CZ75321
      title: Volume 64 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 625
      order: 64
      base_file: 8631.txt
    B700:
      image_group_id: I4CZ75322
      title: Volume 65 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 538
      order: 65
      base_file: B700.txt
    13B8:
      image_group_id: I4CZ75323
      title: Volume 66 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 546
      order: 66
      base_file: 13B8.txt
    BCC2:
      image_group_id: I4CZ75324
      title: Volume 67 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 0
      order: 67
      base_file: BCC2.txt
    DF1C:
      image_group_id: I4CZ75325
      title: Volume 68 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 80
      order: 68
      base_file: DF1C.txt
    4AA8:
      image_group_id: I4CZ75326
      title: Volume 69 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 646
      order: 69
      base_file: 4AA8.txt
    '5494':
      image_group_id: I4CZ75327
      title: Volume 70 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 542
      order: 70
      base_file: 5494.txt
    AE41:
      image_group_id: I4CZ75328
      title: Volume 71 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 0
      order: 71
      base_file: AE41.txt
    0BBE:
      image_group_id: I4CZ75329
      title: Volume 72 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 625
      order: 72
      base_file: 0BBE.txt
    '4344':
      image_group_id: I4CZ75330
      title: Volume 73 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 649
      order: 73
      base_file: 4344.txt
    1D92:
      image_group_id: I4CZ75331
      title: Volume 74 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 0
      order: 74
      base_file: 1D92.txt
    484C:
      image_group_id: I4CZ75332
      title: Volume 75 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 714
      order: 75
      base_file: 484C.txt
    5F49:
      image_group_id: I4CZ75333
      title: Volume 76 of bka' 'gyur/ (he mis bris ma/)
      total_pages: 735
      order: 76
      base_file: 5F49.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
