id: P008105
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W4CZ45313
  title: བཀའ་འགྱུར། ༼ཧེ་མིས་བྲིས་མ།༽
  author: ''
  volumes:
    9f608c17931543cda41e2c01e2c1ff49:
      image_group_id: I4CZ75258
      title: Volume 1 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 1
      total_pages: 513
      base_file: v001.txt
    a8eea6d8bc6c4d8ea4ea5edd0d655561:
      image_group_id: I4CZ75259
      title: Volume 2 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 2
      total_pages: 412
      base_file: v002.txt
    769d436e47784fdf9153072b76c3e9da:
      image_group_id: I4CZ75260
      title: Volume 3 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 3
      total_pages: 855
      base_file: v003.txt
    6442aac05dfa4b4caf7a81d329a38a7e:
      image_group_id: I4CZ75261
      title: Volume 4 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 4
      total_pages: 917
      base_file: v004.txt
    3769925a13d346ecb2f1e404c3df6b76:
      image_group_id: I4CZ75262
      title: Volume 5 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 5
      total_pages: 776
      base_file: v005.txt
    ebfd1715573545daa8ca36db5932b343:
      image_group_id: I4CZ75263
      title: Volume 6 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 6
      total_pages: 937
      base_file: v006.txt
    49d7633c73fa4224a97e7285c19d5487:
      image_group_id: I4CZ75264
      title: Volume 7 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 7
      total_pages: 903
      base_file: v007.txt
    062b85e073d44f8a9e50884322c28afa:
      image_group_id: I4CZ75265
      title: Volume 8 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 8
      total_pages: 674
      base_file: v008.txt
    b561658000cc40f99ee62f6a6d96abc7:
      image_group_id: I4CZ75266
      title: Volume 9 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 9
      total_pages: 659
      base_file: v009.txt
    7a0884f5163441b483a5feba346da350:
      image_group_id: I4CZ75267
      title: Volume 10 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 10
      total_pages: 596
      base_file: v010.txt
    04b8f6522c4546759913f8930f68a708:
      image_group_id: I4CZ75268
      title: Volume 11 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 11
      total_pages: 664
      base_file: v011.txt
    b07853256401430eb46df32efcbc213a:
      image_group_id: I4CZ75269
      title: Volume 12 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 12
      total_pages: 559
      base_file: v012.txt
    394176e1d5f840cca65cd69db816479f:
      image_group_id: I4CZ75270
      title: Volume 13 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 13
      total_pages: 921
      base_file: v013.txt
    05d1794b2d1f450db9cb1d59a3530e42:
      image_group_id: I4CZ75271
      title: Volume 14 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 14
      total_pages: 1031
      base_file: v014.txt
    c38c64c0078d46fbad5ad42c286e9872:
      image_group_id: I4CZ75272
      title: Volume 15 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 15
      total_pages: 933
      base_file: v015.txt
    c6e962d391a741129ce81a95dc0e4ab1:
      image_group_id: I4CZ75273
      title: Volume 16 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 16
      total_pages: 0
    56b458cdeb17476dba3b534ee96c03dd:
      image_group_id: I4CZ75274
      title: Volume 17 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 17
      total_pages: 742
      base_file: v016.txt
    60631409ff9946e2bcc5287e29a771f9:
      image_group_id: I4CZ75275
      title: Volume 18 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 18
      total_pages: 934
      base_file: v017.txt
    d25ef6e24e8941eba8e7562202a7ca14:
      image_group_id: I4CZ75276
      title: Volume 19 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 19
      total_pages: 1161
      base_file: v018.txt
    7d03bd8a476849c48289b9d0799b5e2f:
      image_group_id: I4CZ75277
      title: Volume 20 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 20
      total_pages: 957
      base_file: v019.txt
    462f3652a22640e0852bf2d8619f0926:
      image_group_id: I4CZ75278
      title: Volume 21 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 21
      total_pages: 898
      base_file: v020.txt
    e971bf04aee741b899a01855a0cd3a02:
      image_group_id: I4CZ75279
      title: Volume 22 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 22
      total_pages: 966
      base_file: v021.txt
    54898da7e15c47c4a74eac152a1a73a9:
      image_group_id: I4CZ75280
      title: Volume 23 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 23
      total_pages: 1148
      base_file: v022.txt
    94b68e0882264575ac135d2b2310a9dc:
      image_group_id: I4CZ75281
      title: Volume 24 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 24
      total_pages: 994
      base_file: v023.txt
    3851403f6bef4053a755d3cbc15ff2ff:
      image_group_id: I4CZ75282
      title: Volume 25 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 25
      total_pages: 762
      base_file: v024.txt
    2f84cc4333a546e89993229d8d7ae77f:
      image_group_id: I4CZ75283
      title: Volume 26 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 26
      total_pages: 754
      base_file: v025.txt
    a73c22fa7f5748beb1235a91a9aaca7e:
      image_group_id: I4CZ75284
      title: Volume 27 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 27
      total_pages: 828
      base_file: v026.txt
    f6d8f3d4df9c44bdb0d0900a1821752d:
      image_group_id: I4CZ75285
      title: Volume 28 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 28
      total_pages: 778
      base_file: v027.txt
    6f0171e164ba409bb65259f86d016c5b:
      image_group_id: I4CZ75286
      title: Volume 29 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 29
      total_pages: 575
      base_file: v028.txt
    10eb686dad5248278d5f989db26bdebc:
      image_group_id: I4CZ75287
      title: Volume 30 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 30
      total_pages: 668
      base_file: v029.txt
    b962046d4a2543a88533423d7909db1d:
      image_group_id: I4CZ75288
      title: Volume 31 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 31
      total_pages: 723
      base_file: v030.txt
    6fa3bb7130c14216b045290fe513e840:
      image_group_id: I4CZ75289
      title: Volume 32 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 32
      total_pages: 0
    7ba67a04f3a64769a1cc571968da0e05:
      image_group_id: I4CZ75290
      title: Volume 33 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 33
      total_pages: 1102
      base_file: v031.txt
    3166d3f9336248fe923f6011ca6e649f:
      image_group_id: I4CZ75291
      title: Volume 34 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 34
      total_pages: 1140
      base_file: v032.txt
    eed78fd2005041bbaec9c990b3137d3f:
      image_group_id: I4CZ75292
      title: Volume 35 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 35
      total_pages: 995
      base_file: v033.txt
    e76a3fceff9f46abb6a43b5716a55156:
      image_group_id: I4CZ75293
      title: Volume 36 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 36
      total_pages: 1174
      base_file: v034.txt
    da5c56ad2efa4eaf9ce3e915d140c53e:
      image_group_id: I4CZ75294
      title: Volume 37 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 37
      total_pages: 0
    5e03ca53d9e0489ea3fd8b8657b0ce91:
      image_group_id: I4CZ75295
      title: Volume 38 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 38
      total_pages: 0
    1089fe6e435f4b25ad244ce6acdbc1ac:
      image_group_id: I4CZ75296
      title: Volume 39 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 39
      total_pages: 507
      base_file: v035.txt
    a4027e4649464bb594cb7b5699a76867:
      image_group_id: I4CZ75297
      title: Volume 40 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 40
      total_pages: 490
      base_file: v036.txt
    018a08cab279459cb02754ca989c36e8:
      image_group_id: I4CZ75298
      title: Volume 41 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 41
      total_pages: 871
      base_file: v037.txt
    bcf17ff8bb054964b5c8222006176751:
      image_group_id: I4CZ75299
      title: Volume 42 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 42
      total_pages: 589
      base_file: v038.txt
    f31bc0225add451b8dc54b61add4a94e:
      image_group_id: I4CZ75300
      title: Volume 43 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 43
      total_pages: 318
      base_file: v039.txt
    f62ba6d9dd2245e68f4f35ec7e5f8c4e:
      image_group_id: I4CZ75301
      title: Volume 44 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 44
      total_pages: 541
      base_file: v040.txt
    0fa0eb448ec34175916f51660c7ad101:
      image_group_id: I4CZ75302
      title: Volume 45 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 45
      total_pages: 0
    e373883cecee4f6d977994337d16f033:
      image_group_id: I4CZ75303
      title: Volume 46 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 46
      total_pages: 432
      base_file: v041.txt
    8eb7341233ac4a748b6cba81af5df4d3:
      image_group_id: I4CZ75304
      title: Volume 47 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 47
      total_pages: 580
      base_file: v042.txt
    37776db6e2694ee88cad3a77760fb982:
      image_group_id: I4CZ75305
      title: Volume 48 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 48
      total_pages: 380
      base_file: v043.txt
    2f03c604503a4937ba34b89c3fb0961b:
      image_group_id: I4CZ75306
      title: Volume 49 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 49
      total_pages: 528
      base_file: v044.txt
    464c3a8231b4483f96d266b6651ea511:
      image_group_id: I4CZ75307
      title: Volume 50 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 50
      total_pages: 484
      base_file: v045.txt
    5b2259972de940489354e713425475e1:
      image_group_id: I4CZ75308
      title: Volume 51 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 51
      total_pages: 500
      base_file: v046.txt
    f633dad164d0460787cc136346e31063:
      image_group_id: I4CZ75309
      title: Volume 52 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 52
      total_pages: 528
      base_file: v047.txt
    125636cbdd8341e687391d83f378efda:
      image_group_id: I4CZ75310
      title: Volume 53 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 53
      total_pages: 550
      base_file: v048.txt
    88335da217134c69a2d6548a44274735:
      image_group_id: I4CZ75311
      title: Volume 54 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 54
      total_pages: 677
      base_file: v049.txt
    23ee5a81efd54eada9058609aab0c632:
      image_group_id: I4CZ75312
      title: Volume 55 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 55
      total_pages: 602
      base_file: v050.txt
    e62bb7e64ecb45028407d5d811ff748f:
      image_group_id: I4CZ75313
      title: Volume 56 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 56
      total_pages: 548
      base_file: v051.txt
    ef2aafa6eab54aeba475b3868643ca44:
      image_group_id: I4CZ75314
      title: Volume 57 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 57
      total_pages: 460
      base_file: v052.txt
    79a223d25a42420591ca69a13122d14a:
      image_group_id: I4CZ75315
      title: Volume 58 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 58
      total_pages: 545
      base_file: v053.txt
    84ec104b4f7f41db80e83b8648fc3d70:
      image_group_id: I4CZ75316
      title: Volume 59 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 59
      total_pages: 645
      base_file: v054.txt
    5d162f720f0541eaaaac9c52f8259f40:
      image_group_id: I4CZ75317
      title: Volume 60 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 60
      total_pages: 439
      base_file: v055.txt
    883e6e670d2c4b1b9c7b0f02b9041fe2:
      image_group_id: I4CZ75318
      title: Volume 61 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 61
      total_pages: 684
      base_file: v056.txt
    0870fac2404b41a5bd58f5a4e2971f98:
      image_group_id: I4CZ75319
      title: Volume 62 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 62
      total_pages: 512
      base_file: v057.txt
    f7a339295ce64e0f98f87b41cfbbe536:
      image_group_id: I4CZ75320
      title: Volume 63 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 63
      total_pages: 614
      base_file: v058.txt
    72722c1e93174c72bf9ee9cf196ee6c6:
      image_group_id: I4CZ75321
      title: Volume 64 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 64
      total_pages: 625
      base_file: v059.txt
    20145b6e34f74635b4ef6cdbd378f842:
      image_group_id: I4CZ75322
      title: Volume 65 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 65
      total_pages: 538
      base_file: v060.txt
    2c070d2a184341bdab2e1b36b945a837:
      image_group_id: I4CZ75323
      title: Volume 66 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 66
      total_pages: 546
      base_file: v061.txt
    710889914cbb4a9f8eca6983a4e17019:
      image_group_id: I4CZ75324
      title: Volume 67 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 67
      total_pages: 0
    a028a40508be4444b737d2e838f528b5:
      image_group_id: I4CZ75325
      title: Volume 68 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 68
      total_pages: 80
      base_file: v062.txt
    a7f547f6482f4c20ad57d6ea30b2ac19:
      image_group_id: I4CZ75326
      title: Volume 69 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 69
      total_pages: 646
      base_file: v063.txt
    df84ee93362740819cac836271d74281:
      image_group_id: I4CZ75327
      title: Volume 70 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 70
      total_pages: 542
      base_file: v064.txt
    83afb5c874e5474f8a9d766934bfe52d:
      image_group_id: I4CZ75328
      title: Volume 71 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 71
      total_pages: 0
    0c974f40b651418db7cc16b0d1d018a1:
      image_group_id: I4CZ75329
      title: Volume 72 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 72
      total_pages: 625
      base_file: v065.txt
    88a80a17b189481892f6939356a810e1:
      image_group_id: I4CZ75330
      title: Volume 73 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 73
      total_pages: 649
      base_file: v066.txt
    3acfc1d6d65b4426b99734353b3f4e6d:
      image_group_id: I4CZ75331
      title: Volume 74 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 74
      total_pages: 0
    1bb0f424dcf94b8cbbbcd24e2e9be0d6:
      image_group_id: I4CZ75332
      title: Volume 75 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 75
      total_pages: 714
      base_file: v067.txt
    fa7d316b759149fdb33a89b79febaeec:
      image_group_id: I4CZ75333
      title: Volume 76 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 76
      total_pages: 735
      base_file: v068.txt
    f5b454acf1fe41a09b9645c8b6b2a8b5:
      image_group_id: I4CZ75334
      title: Volume 77 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 77
      total_pages: 592
      base_file: v069.txt
    ca69ec50d407436692fac52b9e9ba98d:
      image_group_id: I4CZ75335
      title: Volume 78 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 78
      total_pages: 683
      base_file: v070.txt
    60e1eb557fbb4a6e8677259e57aeb1dd:
      image_group_id: I4CZ75336
      title: Volume 79 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 79
      total_pages: 638
      base_file: v071.txt
    f4d2a8362c284133acfde10f4de2215b:
      image_group_id: I4CZ75337
      title: Volume 80 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 80
      total_pages: 706
      base_file: v072.txt
    033de138c2ed46d7862325dc5199cea1:
      image_group_id: I4CZ75338
      title: Volume 81 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 81
      total_pages: 682
      base_file: v073.txt
    e61f02819dd740f4881173e45dcd2663:
      image_group_id: I4CZ75339
      title: Volume 82 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 82
      total_pages: 694
      base_file: v074.txt
    5971c8f3b6fd4125a8f05cb4ce9f4a5b:
      image_group_id: I4CZ75340
      title: Volume 83 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 83
      total_pages: 695
      base_file: v075.txt
    e7ae56a4290a4982a201d9938fc56d4c:
      image_group_id: I4CZ75341
      title: Volume 84 of bka' 'gyur/ (he mis bris ma/)
      volume_number: 84
      total_pages: 649
      base_file: v076.txt
