id: P008105
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ45313
  title: བཀའ་འགྱུར། ༼ཧེ་མིས་བྲིས་མ།༽
  author: ''
  volumes:
    f275a3ecc0304090ad551a2346be347f:
      image_group_id: I4CZ75258
      title: ''
      volume_number: 1
      total_pages: 513
    116417c60adc496388c49ecf0ad2753d:
      image_group_id: I4CZ75259
      title: ''
      volume_number: 2
      total_pages: 412
    aae59178369e42098ae22eb3755efc04:
      image_group_id: I4CZ75260
      title: ''
      volume_number: 3
      total_pages: 855
    18bbfe9fee57414f9ef675f4328695db:
      image_group_id: I4CZ75261
      title: ''
      volume_number: 4
      total_pages: 917
    5670714fec764429856353b9f20486fb:
      image_group_id: I4CZ75262
      title: ''
      volume_number: 5
      total_pages: 776
    f8d4f6c45c674c37b8a7664befd6f663:
      image_group_id: I4CZ75263
      title: ''
      volume_number: 6
      total_pages: 937
    4e2d936aac9c4f0386e6be086f8a8374:
      image_group_id: I4CZ75264
      title: ''
      volume_number: 7
      total_pages: 903
    91e7616f527745df9572bf113f05afe6:
      image_group_id: I4CZ75265
      title: ''
      volume_number: 8
      total_pages: 674
    e88b103110b949838913ce4f27c7c532:
      image_group_id: I4CZ75266
      title: ''
      volume_number: 9
      total_pages: 659
    f194f031f22a4aeeb13fdf245e330d6a:
      image_group_id: I4CZ75267
      title: ''
      volume_number: 10
      total_pages: 596
    e7c501f6686b4382ab6d9f7cb0ffb26e:
      image_group_id: I4CZ75268
      title: ''
      volume_number: 11
      total_pages: 664
    834d9201ac50486b9eb3a1a90a49068a:
      image_group_id: I4CZ75269
      title: ''
      volume_number: 12
      total_pages: 559
    c3ea21978f924bc79ab003b77e3b1583:
      image_group_id: I4CZ75270
      title: ''
      volume_number: 13
      total_pages: 921
    b4e0b5a98c5a4260b39cf3009b7cc906:
      image_group_id: I4CZ75271
      title: ''
      volume_number: 14
      total_pages: 1031
    339a8d8a5f8043d095a5b65447f52827:
      image_group_id: I4CZ75272
      title: ''
      volume_number: 15
      total_pages: 933
    0af7f821c3ea49a582cbf4a70875e483:
      image_group_id: I4CZ75273
      title: ''
      volume_number: 16
      total_pages: 0
    9e59539810cf4241b047622117566c36:
      image_group_id: I4CZ75274
      title: ''
      volume_number: 17
      total_pages: 742
    b52ba05c87774a448c7509b2a0e69923:
      image_group_id: I4CZ75275
      title: ''
      volume_number: 18
      total_pages: 934
    acca0f154894407b8035a8aca5b52e80:
      image_group_id: I4CZ75276
      title: ''
      volume_number: 19
      total_pages: 1161
    3d1a14ede03345ca8fca7408d6014350:
      image_group_id: I4CZ75277
      title: ''
      volume_number: 20
      total_pages: 957
    f8beb26ff4304361b998c77cda7f1945:
      image_group_id: I4CZ75278
      title: ''
      volume_number: 21
      total_pages: 898
    20c1a4f39e464f9a99414c6db01baf9c:
      image_group_id: I4CZ75279
      title: ''
      volume_number: 22
      total_pages: 966
    4e16601c0f4c458b9a9521cc9ca62179:
      image_group_id: I4CZ75280
      title: ''
      volume_number: 23
      total_pages: 1148
    ee98e2a6acc64c8fa92e4900e19d4873:
      image_group_id: I4CZ75281
      title: ''
      volume_number: 24
      total_pages: 994
    0a42d73b10f44ef3a8cc171d024101ef:
      image_group_id: I4CZ75282
      title: ''
      volume_number: 25
      total_pages: 762
    686213eb207f49129a6ca5603b2e7536:
      image_group_id: I4CZ75283
      title: ''
      volume_number: 26
      total_pages: 754
    25392181d7554759a36fc2ea74fac1cf:
      image_group_id: I4CZ75284
      title: ''
      volume_number: 27
      total_pages: 828
    93e6fe31571846bab37111bed5e44cc7:
      image_group_id: I4CZ75285
      title: ''
      volume_number: 28
      total_pages: 778
    1132a4772f4144deac99ac1f13ab0e19:
      image_group_id: I4CZ75286
      title: ''
      volume_number: 29
      total_pages: 575
    95cdb05252594d9e8ffc8977a8f08f16:
      image_group_id: I4CZ75287
      title: ''
      volume_number: 30
      total_pages: 668
    d19cbe1c623949848b7dda5776972f2f:
      image_group_id: I4CZ75288
      title: ''
      volume_number: 31
      total_pages: 723
    3450a24d0d6342d18574b92e9ea7cce8:
      image_group_id: I4CZ75289
      title: ''
      volume_number: 32
      total_pages: 0
    43f086a3a3dc408690c53c60a3e946de:
      image_group_id: I4CZ75290
      title: ''
      volume_number: 33
      total_pages: 1102
    260df7f51d1c4f5d8e4b67859c0f2261:
      image_group_id: I4CZ75291
      title: ''
      volume_number: 34
      total_pages: 1140
    6466b41faab14c979f6c9113da0f3fbe:
      image_group_id: I4CZ75292
      title: ''
      volume_number: 35
      total_pages: 995
    6a1bd37241904ee88bd6724e0369372e:
      image_group_id: I4CZ75293
      title: ''
      volume_number: 36
      total_pages: 1174
    887dfb8e2f0844849beff610a02219f9:
      image_group_id: I4CZ75294
      title: ''
      volume_number: 37
      total_pages: 0
    c132128105f6465d90c3adae1e5d72c9:
      image_group_id: I4CZ75295
      title: ''
      volume_number: 38
      total_pages: 0
    140ef75f1146419a8d0d45d56ddb99db:
      image_group_id: I4CZ75296
      title: ''
      volume_number: 39
      total_pages: 507
    5258b41928484611b479ea30dd0db84e:
      image_group_id: I4CZ75297
      title: ''
      volume_number: 40
      total_pages: 490
    3395c66979dd46fda652a255eb609c52:
      image_group_id: I4CZ75298
      title: ''
      volume_number: 41
      total_pages: 871
    f82da21e0af54ead813124863b5c103a:
      image_group_id: I4CZ75299
      title: ''
      volume_number: 42
      total_pages: 589
    285a15fa6dcb49c6b65aaa3de9dc1fa1:
      image_group_id: I4CZ75300
      title: ''
      volume_number: 43
      total_pages: 318
    358e0bbeebff495c9b8547720c935a9c:
      image_group_id: I4CZ75301
      title: ''
      volume_number: 44
      total_pages: 541
    66d50e992e794e1fbe1c4fb357493c72:
      image_group_id: I4CZ75302
      title: ''
      volume_number: 45
      total_pages: 0
    7305554ef9b742d8bead080039ee3323:
      image_group_id: I4CZ75303
      title: ''
      volume_number: 46
      total_pages: 432
    5c5708c17ec046c79b287739561413fc:
      image_group_id: I4CZ75304
      title: ''
      volume_number: 47
      total_pages: 580
    456e268382924798a75f8fb8d5b8bb0a:
      image_group_id: I4CZ75305
      title: ''
      volume_number: 48
      total_pages: 380
    ff7534e36f484385988aab85e300633f:
      image_group_id: I4CZ75306
      title: ''
      volume_number: 49
      total_pages: 528
    774b2ad4cb054743a643726fae960353:
      image_group_id: I4CZ75307
      title: ''
      volume_number: 50
      total_pages: 484
    f98a77d06d6b45bb99a92bda86335959:
      image_group_id: I4CZ75308
      title: ''
      volume_number: 51
      total_pages: 500
    df46483980e74e77a3876d997151e24e:
      image_group_id: I4CZ75309
      title: ''
      volume_number: 52
      total_pages: 528
    948d0a359eb143339bf5dcb2cb82f7af:
      image_group_id: I4CZ75310
      title: ''
      volume_number: 53
      total_pages: 550
    2568fbdadc1441f2809c5010fd6ffac4:
      image_group_id: I4CZ75311
      title: ''
      volume_number: 54
      total_pages: 677
    f4ecfde23a8a45c8bcb2e5707e7d6acd:
      image_group_id: I4CZ75312
      title: ''
      volume_number: 55
      total_pages: 602
    b553482d15564f029a97c444560d6f9e:
      image_group_id: I4CZ75313
      title: ''
      volume_number: 56
      total_pages: 548
    ed07095fa34e46278578eb270c186ce3:
      image_group_id: I4CZ75314
      title: ''
      volume_number: 57
      total_pages: 460
    381055bf81c448b6a2a9cd6c72e783c2:
      image_group_id: I4CZ75315
      title: ''
      volume_number: 58
      total_pages: 545
    ef15bcb1048f4405ab3464d3e6116599:
      image_group_id: I4CZ75316
      title: ''
      volume_number: 59
      total_pages: 645
    f5dec37365064d8b894c9aa1910a94cb:
      image_group_id: I4CZ75317
      title: ''
      volume_number: 60
      total_pages: 439
    f5ba5730052e47459a8dc3aafbc71afd:
      image_group_id: I4CZ75318
      title: ''
      volume_number: 61
      total_pages: 684
    8b1e88f716064f50890dfac769ac1656:
      image_group_id: I4CZ75319
      title: ''
      volume_number: 62
      total_pages: 512
    a0b1db8b1a1845c48fbe0c4ac5417c13:
      image_group_id: I4CZ75320
      title: ''
      volume_number: 63
      total_pages: 614
    d8007ea757484120a993e999978abcf9:
      image_group_id: I4CZ75321
      title: ''
      volume_number: 64
      total_pages: 625
    911caf4336404d53b419836c705b78c5:
      image_group_id: I4CZ75322
      title: ''
      volume_number: 65
      total_pages: 538
    85cc932a5f03497bb14519a6a453f513:
      image_group_id: I4CZ75323
      title: ''
      volume_number: 66
      total_pages: 546
    0fc5b998928b4a0fb357370fdf483a03:
      image_group_id: I4CZ75324
      title: ''
      volume_number: 67
      total_pages: 0
    652a87e76951431faf193b0a85196e15:
      image_group_id: I4CZ75325
      title: ''
      volume_number: 68
      total_pages: 80
    db07e3dd63c6401cbe03d2a11f9f3376:
      image_group_id: I4CZ75326
      title: ''
      volume_number: 69
      total_pages: 646
    7bf363eabddb4151a8a161469262484e:
      image_group_id: I4CZ75327
      title: ''
      volume_number: 70
      total_pages: 542
    162dafa1e79549ecb7ebf2bf447835e2:
      image_group_id: I4CZ75328
      title: ''
      volume_number: 71
      total_pages: 0
    08351ca037a441fcadd7745ca8e4a444:
      image_group_id: I4CZ75329
      title: ''
      volume_number: 72
      total_pages: 625
    7a4159f2dc4242ae88564c60a499d814:
      image_group_id: I4CZ75330
      title: ''
      volume_number: 73
      total_pages: 649
    e148f42101c74a31b551ba62dc597777:
      image_group_id: I4CZ75331
      title: ''
      volume_number: 74
      total_pages: 0
    7d1f28132dc74d129edff9935813889e:
      image_group_id: I4CZ75332
      title: ''
      volume_number: 75
      total_pages: 714
    00a5fee8721c461dbda4cd660504129f:
      image_group_id: I4CZ75333
      title: ''
      volume_number: 76
      total_pages: 735
    6861a44d641d4681bfbd607cb1f1bcbf:
      image_group_id: I4CZ75334
      title: ''
      volume_number: 77
      total_pages: 592
    14deee5729fc4850a9c2d37d7cdcf2c6:
      image_group_id: I4CZ75335
      title: ''
      volume_number: 78
      total_pages: 683
    117003b8dff143a4ab3458888dd14ef7:
      image_group_id: I4CZ75336
      title: ''
      volume_number: 79
      total_pages: 638
    efd87dc927e54bde9e2de94de3a083f9:
      image_group_id: I4CZ75337
      title: ''
      volume_number: 80
      total_pages: 706
    ed31c26343624656b607727924050557:
      image_group_id: I4CZ75338
      title: ''
      volume_number: 81
      total_pages: 682
    17b4c63c97534562967ba80c597fa4a9:
      image_group_id: I4CZ75339
      title: ''
      volume_number: 82
      total_pages: 694
    65e1974848b1445d819dd9b9bce9e60a:
      image_group_id: I4CZ75340
      title: ''
      volume_number: 83
      total_pages: 695
    b126a49ba7004d6fbbf3ec0d55fadca1:
      image_group_id: I4CZ75341
      title: ''
      volume_number: 84
      total_pages: 649
ebook_metadata:
  title: བཀའ་འགྱུར། ༼ཧེ་མིས་བྲིས་མ།༽
  author: ''
  sku: P008105
  cover: cover.jpg
  layers:
  - pagination
